#Application Type
application.type=soa
soabpm.partition=default
soabpm.revision=1.0
#
# soabpm.mds.application=soademo
# list of projects to release & deploy
soabpm.projects=soademo
#
soademo.type=soa
soademo.enabled=true