# Application settings
release=1.0.0
releaseName=soademo
applications.home=../..
# ADF,OSB,SOA&BPM applications
dpl.applications=soademo
#
# MDS settings
mds.applications=
mds.enabled=false
mds.deploy=false
mds.undeploy=true
#mds.undeploy=false
mds.applications.home=../../MDS
#Generiek
Generiek.home=../../Generiek